# Generated by Django 4.1.1 on 2022-11-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('MBD', 'MBD'), ('DBMS', 'DBMS'), ('ENGLISH', 'ENGLISH'), ('MATHS', 'MATHS'), ('DCS', 'DCS'), ('SP', 'SP')], max_length=30),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
