# Generated by Django 4.1.1 on 2022-11-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0002_alter_teacherlogin_subject_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Question',
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('MBD', 'MBD'), ('DCS', 'DCS'), ('ENGLISH', 'ENGLISH'), ('MATHS', 'MATHS'), ('SP', 'SP'), ('DBMS', 'DBMS')], max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
